[package]
name = "rust-client"
version = "0.1.0"
edition = "2021"

[features]
wasm = ["console_error_panic_hook", "wee_alloc", "wasi", "wasm-bindgen", "wasm-bindgen-futures", "wasm-logger", "tracing-wasm", "libp2p/wasm-bindgen", "libp2p/wasm-ext", "libp2p/wasm-ext-websocket", "getrandom/js"]
tokio = ["tokio/full"]
default = ["wasm"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
futures = "0.3.26"
getrandom = { version = "0.2.8" }
libp2p = { version = "0.50.0", features = ["secp256k1", "noise", "mplex", "identify", "ping", "macros", "websocket"] }
log = "0.4.17"
cfg-if = "1.0.0"
particle-protocol = { git = "https://github.com/fluencelabs/rust-peer", branch = "optional-async-std-libp2p" }

#not wasm deps
tokio = { version = "1.25.0", optional = true }

#wasm deps
wasi = { version = "0.11.0", optional = true }
wasm-bindgen = { version = "0.2.84", optional = true }
wasm-bindgen-futures = { version = "0.4.34", optional = true }
wasm-logger = { version = "0.2.0", optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }
wee_alloc = { version = "0.4.2", optional = true }
tracing-wasm = { version = "0.2.1", optional = true }

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'
codegen-units = 1
strip = true

# generated by 'cargo dist init'
[profile.dist]
inherits = "release"
debug = true
split-debuginfo = "packed"


